# Generated by Django 4.2.28 on 2026-04-27 23:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_attendance_unique_together_attendance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القسم')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
            },
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'حضور', 'verbose_name_plural': 'سجلات الحضور'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'دكتور', 'verbose_name_plural': 'الدكاترة'},
        ),
        migrations.AlterModelOptions(
            name='lecture',
            options={'verbose_name': 'محاضرة', 'verbose_name_plural': 'المحاضرات'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'مستوى', 'verbose_name_plural': 'المستويات'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'طالب', 'verbose_name_plural': 'الطلاب'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت التسجيل'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='device_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP الجهاز'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='main.lecture', verbose_name='المحاضرة'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب')], default='absent', max_length=10, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='main.student', verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateField(verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectures', to='main.doctor', verbose_name='الدكتور'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت النهاية'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectures', to='main.level', verbose_name='المستوى'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم المادة'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='start_time',
            field=models.TimeField(verbose_name='وقت البداية'),
        ),
        migrations.AlterField(
            model_name='level',
            name='level_name',
            field=models.CharField(max_length=50, verbose_name='المستوى'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.level', verbose_name='المستوى'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(verbose_name='كود الطالب'),
        ),
        migrations.AddField(
            model_name='level',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='main.department', verbose_name='القسم'),
        ),
    ]
