# Generated by Django 4.2.28 on 2026-04-29 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_department_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='marked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت مسح QR'),
        ),
    ]
