# Generated by Django 4.2.28 on 2026-04-17 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_doctor_level_lecture_doctor_student_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.level'),
        ),
    ]
